name: corsac_jwt
version: 2.0.0+1
description: Lightweight implementation of JSON Web Tokens (JWT).
homepage: https://github.com/corsac-dart/jwt

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  jose: ^0.3.4
  crypto: ^3.0.0
  logging: ^1.0.0
  pointycastle: ^3.9.1

dev_dependencies:
  coverage: ^1.0.0
  lints: ^5.0.0
  test: ^1.17.5

false_secrets:
 - /test/resources/*.pem
