name: corsac_jwt
version: 1.0.0
description: Lightweight implementation of JSON Web Tokens (JWT).
homepage: https://github.com/corsac-dart/jwt

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  asn1lib: ^1.0.0
  crypto: ^3.0.0
  logging: ^1.0.0
  pointycastle: ^3.0.0
  rsa_pkcs: ^2.0.0

dev_dependencies:
  coverage: ^1.0.0
  lints: ^4.0.0
  test: ^1.17.5
